const SAMPLE_ID = '1d0fe384-b1cf-4929-ad5e-1aa544f93dd5';
const SAMPLE_NAME = 'SoftwareOne[e2e] (Test Environment)';
const POOL_ID = 'ccaceadf-6878-4ab4-9fd8-3f6177d0b9d3';

export const CurrentEmployee = {
  'data': {
    'currentEmployee': {
      'id': '73b8772c-7a66-4261-96e6-8e4b494dd25b',
      'jira_connected': false,
      'slack_connected': false,
      '__typename': 'Employee',
    },
  },
};

export const DataSourcesMock = {
  'data': {
    'dataSources': [
      {
        'account_id': 'f34dca74-7ae2-4035-9ae0-3b74f9dc5eb2',
        'id': 'f7322649-49ba-4f32-969a-1cb9d72a29e3',
        'last_getting_metric_attempt_at': 1745405169,
        'last_getting_metric_attempt_error': 'mongo:80: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66c71b502daf0022ab351be2, topology_type: Unknown, servers: [<ServerDescription (\'mongo\', 80) server_type: Unknown, rtt: None, error=NetworkTimeout(\'mongo:80: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\')>]>',
        'last_getting_metrics_at': 1745405169,
        'last_import_at': 1745405169,
        'last_import_attempt_at': 1745405169,
        'last_import_attempt_error': '500 Server Error: Internal Server Error for url: http://restapi:80/restapi/v2/organizations/51afcca1-ac6d-4da2-8040-fc76fa078d64/process_alerts',
        'name': 'Ali dev',
        'parent_id': null,
        'type': 'alibaba_cnr',
        'details': {
          'cost': 378.17856270000095,
          'resources': 75,
          'forecast': 514.09,
          'last_month_cost': 522.2314100399994,
          '__typename': 'DataSourceDetails',
        },
        'config': {
          'access_key_id': null,
          '__typename': 'AlibabaConfig',
        },
        '__typename': 'AlibabaDataSource',
      },
      {
        'account_id': '996403779197',
        'id': '5c925154-e72a-4f6b-a9ab-c7dee9427889',
        'last_getting_metric_attempt_at': 1745405169,
        'last_getting_metric_attempt_error': 'mongo-0.mongo-discovery.default.svc.cluster.local:27017: [Errno 113] No route to host (configured timeouts: connectTimeoutMS: 20000.0ms)',
        'last_getting_metrics_at': 1745405169,
        'last_import_at': 1745405169,
        'last_import_attempt_at': 1745405169,
        'last_import_attempt_error': '500 Server Error: Internal Server Error for url: http://restapi:80/restapi/v2/organizations/51afcca1-ac6d-4da2-8040-fc76fa078d64/process_alerts',
        'name': 'AWS HQ(E2E)',
        'parent_id': null,
        'type': 'aws_cnr',
        'details': {
          'cost': 1396.1336448774027,
          'resources': 283,
          'forecast': 1970.06,
          'last_month_cost': 2406.152078461824,
          '__typename': 'DataSourceDetails',
        },
        'config': {
          'assume_role_account_id': null,
          'assume_role_name': null,
          'access_key_id': 'AKIA6P7SLCZ6TGN2JF7L',
          'linked': false,
          'use_edp_discount': null,
          'cur_version': null,
          'bucket_name': null,
          'bucket_prefix': null,
          'config_scheme': null,
          'region_name': null,
          'report_name': null,
          '__typename': 'AwsConfig',
        },
        '__typename': 'AwsDataSource',
      },
      {
        'account_id': '996403779197',
        'id': 'e349f5c9-23e2-46f4-a825-e39d9525df07',
        'last_getting_metric_attempt_at': 1745405169,
        'last_getting_metric_attempt_error': 'Could not reach any servers in [(\'mongo-0.mongo-discovery.default.svc.cluster.local\', 27017)]. Replica set is configured with internal hostnames or IPs?, Timeout: 30s, Topology Description: <TopologyDescription id: 67932d2c8c34efcd18696c10, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription (\'mongo-0.mongo-discovery.default.svc.cluster.local\', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\'mongo-0.mongo-discovery.default.svc.cluster.local:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\')>]>',
        'last_getting_metrics_at': 1745405169,
        'last_import_at': 1745405169,
        'last_import_attempt_at': 1745405169,
        'last_import_attempt_error': '500 Server Error: Internal Server Error for url: http://restapi:80/restapi/v2/organizations/51afcca1-ac6d-4da2-8040-fc76fa078d64/process_alerts',
        'name': 'AWS Marketing',
        'parent_id': null,
        'type': 'aws_cnr',
        'details': {
          'cost': 660.2440185310019,
          'resources': 42,
          'forecast': 892.46,
          'last_month_cost': 878.1792224037625,
          '__typename': 'DataSourceDetails',
        },
        'config': {
          'client_id': '990d710f-9527-4155-98da-7e1a0e637406',
          'expense_import_scheme': 'usage',
          'subscription_id': '2d2f328c-1407-4e5e-ba59-1cbad182940f',
          'tenant': '1dc9b339-fadb-432e-86df-423c38a0fcb8',
          'export_name': null,
          'container': null,
          'directory': null,
          '__typename': 'AzureSubscriptionConfig',
        },
        '__typename': 'AzureSubscriptionDataSource',
      },
      {
        'account_id': '21f20f21-4b20-4317-b9d3-7ab10591d9b9',
        'id': '1b5d53f3-48a2-414a-a8ae-69f468b2fbc6',
        'last_getting_metric_attempt_at': 1745405169,
        'last_getting_metric_attempt_error': '\'value\'',
        'last_getting_metrics_at': 1745405169,
        'last_import_at': 1745405169,
        'last_import_attempt_at': 1745405169,
        'last_import_attempt_error': '52faba002e2143309ecdd8f89c186ff3',
        'name': 'Azure QA',
        'parent_id': null,
        'type': 'azure_cnr',
        'details': {
          'cost': 198.53014163656061,
          'resources': 46,
          'forecast': 266.12,
          'last_month_cost': 249.22043772368775,
          '__typename': 'DataSourceDetails',
        },
        'config': {
          'client_id': null,
          'expense_import_scheme': null,
          'subscription_id': null,
          'tenant': null,
          'export_name': null,
          'container': null,
          'directory': null,
          '__typename': 'AzureSubscriptionConfig',
        },
        '__typename': 'AzureSubscriptionDataSource',
      },
      {
        'account_id': '490d6f9a-bfa0-4478-a3ed-3fc4075366f2',
        'id': '42ede413-a8a1-43f0-b9b2-89e49c4b385f',
        'last_getting_metric_attempt_at': 1745405169,
        'last_getting_metric_attempt_error': 'mongo:80: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67932d888c34efcd18696c12, topology_type: Unknown, servers: [<ServerDescription (\'mongo\', 80) server_type: Unknown, rtt: None, error=NetworkTimeout(\'mongo:80: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\')>]>',
        'last_getting_metrics_at': 1745405169,
        'last_import_at': 1745405169,
        'last_import_attempt_at': 1745405169,
        'last_import_attempt_error': '500 Server Error: Internal Server Error for url: http://restapi:80/restapi/v2/organizations/51afcca1-ac6d-4da2-8040-fc76fa078d64/process_alerts',
        'name': 'Dev environment',
        'parent_id': null,
        'type': 'azure_cnr',
        'details': {
          'cost': 618.664070933299,
          'resources': 134,
          'forecast': 856.1,
          'last_month_cost': 954.3223329093478,
          '__typename': 'DataSourceDetails',
        },
        'config': {
          'client_id': null,
          'expense_import_scheme': null,
          'subscription_id': null,
          'tenant': null,
          'export_name': null,
          'container': null,
          'directory': null,
          '__typename': 'AzureSubscriptionConfig',
        },
        '__typename': 'AzureSubscriptionDataSource',
      },
      {
        'account_id': '6300b5ec-d407-4b0c-9890-504a9c8cc365',
        'id': '760d2e7b-1497-4c58-bb6c-1e55f2864b09',
        'last_getting_metric_attempt_at': 1745405169,
        'last_getting_metric_attempt_error': null,
        'last_getting_metrics_at': 1745405169,
        'last_import_at': 1745405169,
        'last_import_attempt_at': 1745405169,
        'last_import_attempt_error': '500 Server Error: Internal Server Error for url: http://restapi:80/restapi/v2/organizations/51afcca1-ac6d-4da2-8040-fc76fa078d64/process_alerts',
        'name': 'Environment',
        'parent_id': null,
        'type': 'environment',
        'details': {
          'cost': 45.936000000000035,
          'resources': 4,
          'forecast': 62.64,
          'last_month_cost': 64.7279999880791,
          '__typename': 'DataSourceDetails',
        },
        '__typename': 'EnvironmentDataSource',
      },
      {
        'account_id': '863d73c5-7865-4d7f-97be-5772718074b6',
        'id': '6496fa15-0877-48be-b8f7-46c4c666299d',
        'last_getting_metric_attempt_at': 1745405169,
        'last_getting_metric_attempt_error': 'Deadline of 120.0s exceeded while calling target function, last exception: 504 Deadline Exceeded',
        'last_getting_metrics_at': 1745405169,
        'last_import_at': 1745405169,
        'last_import_attempt_at': 1745405169,
        'last_import_attempt_error': '500 Server Error: Internal Server Error for url: http://restapi:80/restapi/v2/organizations/51afcca1-ac6d-4da2-8040-fc76fa078d64/process_alerts',
        'name': 'GCP dev',
        'parent_id': null,
        'type': 'gcp_cnr',
        'details': {
          'cost': 679.0680940000016,
          'resources': 101,
          'forecast': 899.66,
          'last_month_cost': 782.3755328678072,
          '__typename': 'DataSourceDetails',
        },
        'config': {
          'billing_data': null,
          'pricing_data': null,
          '__typename': 'GcpConfig',
        },
        '__typename': 'GcpDataSource',
      },
      {
        'account_id': 'b8d64491-f7e3-4c29-820e-0f743578f6a6',
        'id': '1e309056-acb7-40f7-9de0-2b3591f344f4',
        'last_getting_metric_attempt_at': 1745405169,
        'last_getting_metric_attempt_error': 'mongo:80: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 678e2e46b6cc33f658afa584, topology_type: Unknown, servers: [<ServerDescription (\'mongo\', 80) server_type: Unknown, rtt: None, error=NetworkTimeout(\'mongo:80: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\')>]>',
        'last_getting_metrics_at': 1745405169,
        'last_import_at': 1745405169,
        'last_import_attempt_at': 1745405169,
        'last_import_attempt_error': '500 Server Error: Internal Server Error for url: http://restapi:80/restapi/v2/organizations/51afcca1-ac6d-4da2-8040-fc76fa078d64/process_alerts',
        'name': 'K8s dev',
        'parent_id': null,
        'type': 'kubernetes_cnr',
        'details': {
          'cost': 263.0108490217634,
          'resources': 139,
          'forecast': 338.29,
          'last_month_cost': 235.6914593375433,
          '__typename': 'DataSourceDetails',
        },
        'config': {
          'cost_model': {
            'cpu_hourly_cost': 0.006,
            'memory_hourly_cost': 0.004,
            '__typename': 'K8CostModelConfig',
          },
          'custom_price': null,
          'cluster_name': 'dev-cluster',
          'user': 'optscale',
          '__typename': 'K8sConfig',
        },
        '__typename': 'K8sDataSource',
      },
    ],
  },
};

export const poolsMock =
  {
    'deleted_at': 0,
    'id': POOL_ID,
    'created_at': 1743693482,
    'limit': 15000,
    'name': SAMPLE_NAME,
    'organization_id': SAMPLE_ID,
    'parent_id': null,
    'purpose': 'business_unit',
    'default_owner_id': '4447ab7b-da32-4d3e-8840-f244ed505c05',
    'default_owner_name': 'Francesco',
    'unallocated_limit': 154387,
  };
